name: Test Terraform Reviewer

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Python syntax
        run: |
          python -m py_compile terraform_reviewer/*.py

      - name: Import test
        run: |
          python -c "import terraform_reviewer; print('Import successful')"

  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Run flake8
        run: |
          flake8 terraform_reviewer/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Check formatting with black
        run: |
          black --check terraform_reviewer/

  integration-test:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'
    
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Create test Terraform files
        run: |
          mkdir -p test-terraform
          cat > test-terraform/main.tf << 'EOF'
          provider "aws" {
            region = "ap-northeast-1"
          }
          
          resource "aws_s3_bucket" "test" {
            bucket = "test-bucket-${random_id.bucket_suffix.hex}"
          }
          
          resource "random_id" "bucket_suffix" {
            byte_length = 8
          }
          EOF

      - name: Terraform Init
        run: |
          cd test-terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd test-terraform
          terraform plan -no-color > plan.txt

      - name: Test Terraform Reviewer Action
        uses: ./
        with:
          aws_region: ap-northeast-1
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          model_id: anthropic.claude-3-haiku-20240307-v1:0
          terraform_plan_file: test-terraform/plan.txt
          github_token: ${{ secrets.GITHUB_TOKEN }}